iadsstgapphost03
*** Found local files:
***   * Airflow/logs/dag_id=C1_Clipper_Worker/run_id=scheduled__2025-02-03T05:05:00+00:00/task_id=clip_generator_sub_worker/map_index=1/attempt=2.log
[2025-02-03T07:06:00.822+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-02-03T07:06:00.856+0000] {__init__.py:51} DEBUG - Loading core task runner: StandardTaskRunner
[2025-02-03T07:06:00.882+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-02-03T07:06:00.888+0000] {base_task_runner.py:68} DEBUG - Planning to run as the  user
[2025-02-03T07:06:00.891+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> from DB
[2025-02-03T07:06:00.912+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Task Instance State' PASSED: True, Task state queued was valid.
[2025-02-03T07:06:00.913+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Task has been mapped' PASSED: True, The task has been mapped
[2025-02-03T07:06:00.913+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-03T07:06:00.913+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-03T07:06:00.913+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Task Instance Not Running' PASSED: True, Task is not in running state.
[2025-02-03T07:06:00.919+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]>
[2025-02-03T07:06:00.922+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Task has been mapped' PASSED: True, The task has been mapped
[2025-02-03T07:06:00.926+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Pool Slots Available' PASSED: True, There are enough open slots in default_pool to execute the task
[2025-02-03T07:06:00.926+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Not In Retry Period' PASSED: True, The task instance was not marked for retrying.
[2025-02-03T07:06:00.927+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Task Concurrency' PASSED: True, Task concurrency is not set.
[2025-02-03T07:06:00.927+0000] {taskinstance.py:1168} DEBUG - <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]> dependency 'Previous Dagrun State' PASSED: True, The task did not have depends_on_past set.
[2025-02-03T07:06:00.929+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [queued]>
[2025-02-03T07:06:00.929+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 1
[2025-02-03T07:06:00.943+0000] {taskinstance.py:1382} INFO - Executing <Mapped(_PythonDecoratedOperator): clip_generator_sub_worker> on 2025-02-03 05:05:00+00:00
[2025-02-03T07:06:00.949+0000] {standard_task_runner.py:57} INFO - Started process 46530 to run task
[2025-02-03T07:06:00.956+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'C1_Clipper_Worker', 'clip_generator_sub_worker', 'scheduled__2025-02-03T05:05:00+00:00', '--job-id', '298784', '--raw', '--subdir', '/home/ladsadmin/FGICWebApp/Airflow/dags/c1_clipper_worker_dag.py', '--cfg-path', '/tmp/tmpva1jknop', '--map-index', '1']
[2025-02-03T07:06:00.962+0000] {standard_task_runner.py:85} INFO - Job 298784: Subtask clip_generator_sub_worker
[2025-02-03T07:06:00.962+0000] {cli_action_loggers.py:67} DEBUG - Calling callbacks: [<function default_action_log at 0x7fcb354b3f40>]
[2025-02-03T07:06:01.041+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-02-03T07:06:01.048+0000] {task_command.py:416} INFO - Running <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> on host iadsstgapphost03
[2025-02-03T07:06:01.048+0000] {settings.py:373} DEBUG - Disposing DB connection pool (PID 46530)
[2025-02-03T07:06:01.049+0000] {settings.py:234} DEBUG - Setting up DB connection pool (PID 46530)
[2025-02-03T07:06:01.049+0000] {settings.py:305} DEBUG - settings.prepare_engine_args(): Using NullPool
[2025-02-03T07:06:01.050+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:01.125+0000] {taskinstance.py:1094} DEBUG - previous_execution_date was called
[2025-02-03T07:06:01.132+0000] {taskinstance.py:925} DEBUG - Clearing XCom data
[2025-02-03T07:06:01.158+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields.write with retries. Try 1 of 3
[2025-02-03T07:06:01.172+0000] {retries.py:93} DEBUG - Running RenderedTaskInstanceFields._do_delete_old_records with retries. Try 1 of 3
[2025-02-03T07:06:01.196+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='C1_Clipper_Worker' AIRFLOW_CTX_TASK_ID='clip_generator_sub_worker' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T05:05:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-03T05:05:00+00:00'
[2025-02-03T07:06:01.196+0000] {__init__.py:116} DEBUG - Preparing lineage inlets and outlets
[2025-02-03T07:06:01.197+0000] {__init__.py:157} DEBUG - inlets: [], outlets: []
[2025-02-03T07:06:01.197+0000] {c1_clipper_worker_dag.py:31} INFO - Clipper Worker started its work.
[2025-02-03T07:06:01.656+0000] {_base_logger.py:40} INFO - {"worker": "CTPIClipperWorker", "msg": "CTPIClipperWorker Started.", "level": "INFO", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.661+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Clip Folder Path fetched from NewClipReuest table.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.663+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Clip folder path is:/home/ladsadmin/share/stgrasterstore/clipped_images/fba1c675-8df3-41ff-9ec6-e0690a6b759f", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.668+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Clip images are :<QuerySet [<ClipImages: ClipImages object (200ae71b-543a-474e-b4b1-22b841b91ce0)>]>", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.671+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Clip image is :ClipImages object (200ae71b-543a-474e-b4b1-22b841b91ce0)", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.678+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Target Image ID is :TargetImage object (728)", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.680+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Method for Clip image is About to Start.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.682+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Generating DataFrame.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.684+0000] {_base_logger.py:66} DEBUG - {"worker": "ClipperService", "msg": "Converting Django polygon to Geo Dataframe.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.730+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Dataframe Generated.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.734+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "band name for image is:Single_Band_Image", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.736+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Output Path is: /home/ladsadmin/share/stgrasterstore/clipped_images/fba1c675-8df3-41ff-9ec6-e0690a6b759f/200ae71b-543a-474e-b4b1-22b841b91ce0clipped_request_35.tif", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.738+0000] {_base_logger.py:66} DEBUG - {"worker": "CTPIClipperWorker", "msg": "Started Clipping for tif file.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.740+0000] {_base_logger.py:66} DEBUG - {"worker": "ClipperService", "msg": "Open the file using rasterio.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.743+0000] {env.py:272} DEBUG - Entering env context: <rasterio.env.Env object at 0x7fcb0abded10>
[2025-02-03T07:06:01.743+0000] {env.py:274} DEBUG - Starting outermost env
[2025-02-03T07:06:01.743+0000] {env.py:321} DEBUG - No GDAL environment exists
[2025-02-03T07:06:01.743+0000] {env.py:324} DEBUG - New GDAL environment <rasterio._env.GDALEnv object at 0x7fcb0abde9e0> created
[2025-02-03T07:06:01.841+0000] {env.py:326} DEBUG - Installing FilePath filesystem handler plugin...
[2025-02-03T07:06:01.842+0000] {env.py:326} DEBUG - GDAL data found in package: path='/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/gdal_data'.
[2025-02-03T07:06:01.843+0000] {env.py:326} DEBUG - PROJ data found in package: path='/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/proj_data'.
[2025-02-03T07:06:01.843+0000] {env.py:326} DEBUG - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7fcb0abde9e0>.
[2025-02-03T07:06:01.844+0000] {env.py:296} DEBUG - Entered env context: <rasterio.env.Env object at 0x7fcb0abded10>
[2025-02-03T07:06:01.844+0000] {__init__.py:304} DEBUG - Sharing flag: 0
[2025-02-03T07:06:01.911+0000] {__init__.py:304} DEBUG - Nodata success: 1, Nodata value: 0.000000
[2025-02-03T07:06:01.912+0000] {__init__.py:304} DEBUG - Nodata success: 1, Nodata value: 0.000000
[2025-02-03T07:06:01.912+0000] {__init__.py:304} DEBUG - Dataset <open DatasetReader name='/home/ladsadmin/share/nfsstgrasterstore/0b6a4cb4-6926-46ab-8ce7-944386e5706b_2025-01-25_10-43-41.img' mode='r'> is started.
[2025-02-03T07:06:01.913+0000] {env.py:300} DEBUG - Exiting env context: <rasterio.env.Env object at 0x7fcb0abded10>
[2025-02-03T07:06:01.913+0000] {env.py:361} DEBUG - Cleared existing <rasterio._env.GDALEnv object at 0x7fcb0abde9e0> options
[2025-02-03T07:06:01.913+0000] {env.py:362} DEBUG - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7fcb0abde9e0>.
[2025-02-03T07:06:01.914+0000] {env.py:306} DEBUG - Exiting outermost env
[2025-02-03T07:06:01.914+0000] {env.py:313} DEBUG - Exited env context: <rasterio.env.Env object at 0x7fcb0abded10>
[2025-02-03T07:06:01.914+0000] {env.py:272} DEBUG - Entering env context: <rasterio.env.Env object at 0x7fcb0abdeda0>
[2025-02-03T07:06:01.914+0000] {env.py:274} DEBUG - Starting outermost env
[2025-02-03T07:06:01.914+0000] {env.py:321} DEBUG - No GDAL environment exists
[2025-02-03T07:06:01.915+0000] {env.py:324} DEBUG - New GDAL environment <rasterio._env.GDALEnv object at 0x7fcb0abde9e0> created
[2025-02-03T07:06:01.915+0000] {env.py:326} DEBUG - GDAL data found in package: path='/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/gdal_data'.
[2025-02-03T07:06:01.916+0000] {env.py:326} DEBUG - PROJ data found in package: path='/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/proj_data'.
[2025-02-03T07:06:01.916+0000] {env.py:326} DEBUG - Started GDALEnv: self=<rasterio._env.GDALEnv object at 0x7fcb0abde9e0>.
[2025-02-03T07:06:01.916+0000] {env.py:296} DEBUG - Entered env context: <rasterio.env.Env object at 0x7fcb0abdeda0>
[2025-02-03T07:06:01.917+0000] {_base_logger.py:66} DEBUG - {"worker": "ClipperService", "msg": "Re-projecting the GeoJSON to match the raster CRS if needed.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.939+0000] {_base_logger.py:66} DEBUG - {"worker": "ClipperService", "msg": "Converting GeoDataFrame to GeoJSON format.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.943+0000] {_base_logger.py:66} DEBUG - {"worker": "ClipperService", "msg": "Converting the GeoJSON geometries to a format compatible with rasterio.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:01.947+0000] {_base_logger.py:66} DEBUG - {"worker": "ClipperService", "msg": "Cliping the input raster using the provided shapes.", "level": "DEBUG", "clip_request": "NewClipRequest object (35)"}
[2025-02-03T07:06:05.980+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:06.004+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:11.080+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:11.112+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:14.563+0000] {features.py:366} DEBUG - Path: _UnparsedPath(path='MEM:::DATAPOINTER=140502799089680,PIXELS=87953,LINES=82253,BANDS=1,DATATYPE=Byte'), mode: r+, driver: None
[2025-02-03T07:06:14.665+0000] {features.py:366} DEBUG - Nodata success: 0, Nodata value: 0.000000
[2025-02-03T07:06:16.160+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:16.185+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:21.243+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:21.270+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:26.334+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:26.364+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:31.426+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:31.454+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:36.520+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:36.546+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:41.611+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:41.637+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:46.698+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:46.721+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:51.789+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:51.817+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:06:56.870+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:06:56.903+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:07:01.963+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:07:01.992+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:07:07.051+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:07:07.074+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:07:12.134+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:07:12.158+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:07:17.244+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:07:17.276+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:07:22.853+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:07:23.791+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:07:29.642+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:07:29.963+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:07:36.669+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:07:41.728+0000] {job.py:216} DEBUG - [heartbeat]
[2025-02-03T07:07:46.269+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-02-03T07:07:46.353+0000] {local_task_job_runner.py:115} ERROR - Received SIGTERM. Terminating subprocesses
[2025-02-03T07:07:46.380+0000] {process_utils.py:131} INFO - Sending 15 to group 46530. PIDs of all processes in the group: [46530]
[2025-02-03T07:07:46.402+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 46530
[2025-02-03T07:08:21.723+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-03T07:08:21.780+0000] {env.py:300} DEBUG - Exiting env context: <rasterio.env.Env object at 0x7fcb0abdeda0>
[2025-02-03T07:08:21.797+0000] {env.py:361} DEBUG - Cleared existing <rasterio._env.GDALEnv object at 0x7fcb0abde9e0> options
[2025-02-03T07:08:21.799+0000] {env.py:362} DEBUG - Stopped GDALEnv <rasterio._env.GDALEnv object at 0x7fcb0abde9e0>.
[2025-02-03T07:08:21.802+0000] {env.py:306} DEBUG - Exiting outermost env
[2025-02-03T07:08:21.803+0000] {env.py:313} DEBUG - Exited env context: <rasterio.env.Env object at 0x7fcb0abdeda0>
[2025-02-03T07:08:21.864+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:08:22.892+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 221, in execute
    return_value = super().execute(context)
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ladsadmin/FGICWebApp/Airflow/dags/c1_clipper_worker_dag.py", line 37, in clip_generator_sub_worker
    worker.start(clip_request)
  File "/home/ladsadmin/FGICWebApp/IngestionEngine/workers/ctpi_clipper_worker.py", line 336, in start
    self.process_started_worker(clip_request)
  File "/home/ladsadmin/FGICWebApp/IngestionEngine/workers/ctpi_clipper_worker.py", line 192, in process_started_worker
    clip_service.clip_using_dataframe(
  File "/home/ladsadmin/FGICWebApp/Processor/services/clipper_service.py", line 68, in clip_using_dataframe
    out_image, out_transform = mask(src, shapes, crop=True, invert=False)
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/mask.py", line 178, in mask
    shape_mask, transform, window = raster_geometry_mask(
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/mask.py", line 104, in raster_geometry_mask
    mask = geometry_mask(shapes, transform=transform, invert=invert,
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/env.py", line 398, in wrapper
    return f(*args, **kwds)
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/features.py", line 67, in geometry_mask
    return rasterize(
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/env.py", line 398, in wrapper
    return f(*args, **kwds)
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/rasterio/features.py", line 366, in rasterize
    _rasterize(valid_shapes, out, transform, all_touched, merge_alg)
  File "rasterio/_features.pyx", line 373, in rasterio._features._rasterize
  File "rasterio/_base.pyx", line 450, in rasterio._base.DatasetBase.__exit__
  File "rasterio/_base.pyx", line 441, in rasterio._base.DatasetBase.close
  File "/usr/lib/python3.10/contextlib.py", line 582, in close
    def close(self):
  File "/home/ladsadmin/FGICWebApp/venv/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1634, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2025-02-03T07:08:23.004+0000] {taskinstance.py:844} DEBUG - Refreshing TaskInstance <TaskInstance: C1_Clipper_Worker.clip_generator_sub_worker scheduled__2025-02-03T05:05:00+00:00 map_index=1 [running]> from DB
[2025-02-03T07:08:23.022+0000] {taskinstance.py:2430} DEBUG - Task Duration set to 142.099604
[2025-02-03T07:08:23.085+0000] {taskinstance.py:1458} DEBUG - Clearing next_method and next_kwargs.
[2025-02-03T07:08:23.096+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=C1_Clipper_Worker, task_id=clip_generator_sub_worker, map_index=1, execution_date=20250203T050500, start_date=20250203T070600, end_date=20250203T070823
[2025-02-03T07:08:23.459+0000] {cli_action_loggers.py:85} DEBUG - Calling callbacks: []
[2025-02-03T07:08:23.472+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 298784 for task clip_generator_sub_worker (Task received SIGTERM signal; 46530)
[2025-02-03T07:08:24.067+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=46530, status='terminated', exitcode=1, started='07:06:00') (46530) terminated with exit code 1
[2025-02-03T07:08:24.084+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 143
[2025-02-03T07:08:24.384+0000] {dagrun.py:734} DEBUG - number of tis tasks for <DagRun C1_Clipper_Worker @ 2025-02-03 05:05:00+00:00: scheduled__2025-02-03T05:05:00+00:00, state:running, queued_at: 2025-02-03 07:05:01.025547+00:00. externally triggered: False>: 0 task(s)
[2025-02-03T07:08:24.396+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-03T07:08:24.419+0000] {process_utils.py:131} INFO - Sending 15 to group 46530. PIDs of all processes in the group: []
[2025-02-03T07:08:24.420+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 46530
[2025-02-03T07:08:24.423+0000] {process_utils.py:100} INFO - Sending the signal 15 to process 46530 as process group is missing.
